### ISSUE TITLE
question about the code in the file infKL_cvi

### ISSUE THREAD

**Issue by Fangwq** [emtiyaz/cvi#1]
Hello, professor, I have a question about the code in the file `infKL_cvi.m`,  where does the `-2` come from in `tlambda2` updating (line 52 in the file `infKL_cvi.m` )?
```
  tlambda1 = (1-beta).*tlambda1+ beta.*( df-2*(dv.*post_m) );
  tlambda2 = (1-beta).*tlambda2 + beta.*(-2*dv);
```
Any details do I have to catch up? (According to the supplementary material (`equation 31`) of the KL_cvi paper, it seems to be `1`). Thanks in advance.

**Comment by emtiyaz** [comment]
Thanks for the question. It depends on which parametrization you would like tlambda2 to be in. If tlambda2 corresponds to the local natural parmaeter then it should be dv. Since natural parameter is -half*variance, multiplying by -2 makes it the precision parameter (inverse of the variance).

Hope this makes sense.

**Comment by Fangwq** [comment]
@emtiyaz,  thanks for your clarification. However, Does it not contradict with the ` df-2*(dv.*post_m) ` in `tlambda1 ` updating ? After all, 
it could be concluded that
```
d(m)/d(tlambda1) = 1, d(v)/d(tlambda1) = -2 post_m
d(m)/d(tlambda2) = 0, d(v)/d(tlambda2) = -2
```
But you state that `tlambda2 = -1/2 v`. Does anything I went wrong here?

**Comment by emtiyaz** [comment]
My opinion is that it does not contradict with the df-2*(dv.*post_m) in tlambda1. The definition of tlambda2 is independent of tlambda1, so you can arbitrarily scale it up or down.

**Comment by Fangwq** [comment]
OK, by the way, what's the definition of the other natural parameter in the code infKL_cvi.m?

**Comment by emtiyaz** [comment]
Line 38-40 are the important one in this regard, where clearly tlambda2 includes the -1/2 inside (see Appendix E.1 for an example of the definition of tlambda2 where -1/2 is not included).

 % Gaussian pseudo-observation
  pseudo_y = tlambda1./tlambda2;
  sW = sqrt(abs(tlambda2)); % noise precision
