### ISSUE TITLE
question about `epComputeParams` function in the file `infKL_cvi`

### ISSUE THREAD

**Issue by Fangwq** [emtiyaz/cvi#2]
Dear professor, would you mind telling me what I should refer to to understand the function`epComputeParams` in the file `infKL_cvi`?

**Comment by emtiyaz** [comment]
Thanks for the question. It is an implementation borrowed from Hannes Nickisch's original code who wrote the GPML toolbox. It implements Eq. 3.65 from GP book to computer marginal likelihood with EP site parameters.

I show here that if you replace EP site parameters by the variational "site" parameters (tlambda1, tlambda2), then it still gives you a similar answer to the variational marginal likelihood. See Fig. 4.15 in my PhD thesis for a wonderful but no so famous result. https://open.library.ubc.ca/cIRcle/collections/ubctheses/24/items/1.0052219

Also see this paper by Paul Chang et al. where they show how the EP updates are similar to CVI updates. https://arxiv.org/abs/2007.04731

And a new paper on dual parameterization where the new marginal likelihood is used to speed up SVGP. https://arxiv.org/abs/2111.03412

**Comment by Fangwq** [comment]
Thanks for your clarification!
